[package]
name = "gel"
version = "0.1.0"
edition = "2024"

[dependencies]
boa_engine = "0.20.0"
geo = "0.31.0"
depth_tree = { path = "../depth_tree", features=["geo-integration", "svg-integration"] }
geo-clipper = "0.9.0"

[dev-dependencies]
